spring.application.name=Employee_metadata
server.port=8080

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/EmployeeMetaData
spring.datasource.username=dev_user
spring.datasource.password=dev_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
# This helps see if your seeder is working:
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create
spring.h2.console.enabled=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true