spring.application.name=Employee_metadata
server.port=5433

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/algo_test_db
spring.datasource.username=donovr
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.org.hibernate.SQL=DEBUG

# JPA / Hibernate
# This helps see if your seeder is working:
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true